---
sudo: false
language: node_js
matrix:
    fast_finish: true
    include:
        - os: linux
          node_js: 0.10
          env: CXX=g++-4.8
        - os: linux
          node_js: 4
          env: CXX=g++-4.8
        - os: linux
          node_js: 6
          env: CXX=g++-4.8
        - os: osx
          node_js: 4
env:
    global:
        - COZY_DESKTOP_DIR=tmp
        - NODE_ENV=test
        - NPM_CONFIG_PROGRESS=false
services:
    - couchdb
cache:
    directories:
        - node_modules
        - cozy-data-system/node_modules
        - cozy-proxy/node_modules
        - cozy-files/node_modules
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

# install cozy stack for integration test
before_install:
    - cd
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        npm install -g pouchdb-server;
        pouchdb-server -n -m -p 5984 &
      fi
    - export INDEXES_PATH=$HOME/build/indexes
    - mkdir -p $INDEXES_PATH
    - TESTED_NODE=$(node -v)
    - nvm install 4
    - nvm use 4
    - travis_retry npm -g install npm@latest-2
    - npm install forever coffee-script -g
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - git checkout origin/development
    - travis_retry npm install #data-system
    - npm run build
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log -e forever-ds-err.log build/server.js
    - sleep 5
    - pwd
    - cd
    - git clone git://github.com/cozy/cozy-proxy.git
    - cd cozy-proxy
    - git checkout origin/development
    - travis_retry npm install #proxy
    - npm run build
    - pwd
    - NAME=proxy TOKEN=token forever start -o forever-proxy.log -e forever-proxy-err.log build/server.js
    - sleep 5
    - 'curl -X POST -H "Content-Type: application/json" -d "{ \"email\": \"cozytest@cozycloud.cc\", \"password\": \"cozytest\", \"timezone\":\"Europe/Paris\"}" http://127.0.0.1:9104/register'
    - cd
    - git clone git://github.com/cozy/cozy-files.git
    - cd cozy-files
    - travis_retry npm install #files
    - pwd
    - cd ~/cozy-data-system
    - coffee commands.coffee test-install files ../cozy-files/package.json
    - pwd
    - cd ~/cozy-files
    - NAME=files TOKEN=apptoken forever start -o forever-files.log -e forever-files-err.log build/server.js
    - sleep 3
    - nvm use $TESTED_NODE
    - cd $HOME/build/cozy-labs/cozy-desktop
    - pwd
    - mkdir /tmp/cozy-desktop
    - ln -s /tmp/cozy-desktop tmp

script:
    - npm run build
    - npm run lint
    - npm run test

after_failure:
    - pwd
    - $CXX --version
    - ps aux | grep server.js
    - netstat -lntp
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-data-system/forever-ds-err.log
    - cat ~/cozy-proxy/forever-proxy.log
    - cat ~/cozy-proxy/forever-proxy-err.log
    - cat ~/cozy-files/forever-files.log
    - cat ~/cozy-files/forever-files-err.log
    - curl -v http://localhost:9101/
    - curl -v http://localhost:9104/
    - curl -v http://localhost:9121/
